### ISSUE TITLE
Task List 1

### ISSUE THREAD

**Issue by PhilipPurwoko** [AlfanMask/Job-Seeker#4]
**Front End**
- [x] Choose register account type page
- [x] Register page for company
- [x] Register page for employer

**Back End**
- [x] Fully functional login register account (company & employer)
- [x] Working session login
- [x] Setup table multilevel user (company & employer)
- [x] Setup columns and rows database (postgresql)
- [x] Register form validation
- [x] Login form validation

**Comment by AlfanMask** [comment]
Finished All Register Pages

**Comment by PhilipPurwoko** [comment]
Finished all
